version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fgo-farming-solver"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-y7balmz9na0d"
s3_prefix = "fgo-farming-solver"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "fgo-farming-solver-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-y7balmz9na0d"
s3_prefix = "fgo-farming-solver-dev"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"dev\""
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "fgo-farming-solver-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-y7balmz9na0d"
s3_prefix = "fgo-farming-solver-prod"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"prod\""
image_repositories = []
