AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fgo-farming-solver

  Sample SAM Template for fgo-farming-solver

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  FgoFarmingSolverFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: fgo_farming_solver/
      Handler: main.handler
      Runtime: python3.8
      Environment:
        Variables:
          BUCKET_NAME: fgodrop
          TABLE_NAME: fgo-farming-solver-results
      Events:
        FgoFarmingSolver:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fgo-farming-solver
            Method: get
      MemorySize: 1024
      Policies:
        - S3ReadPolicy:
            BucketName: fgodrop
        - DynamoDBWritePolicy:
            TableName: fgo-farming-solver-results
  FgoFarmingSolverResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: fgo-farming-solver-results
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
          

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FgoFarmingSolverApi:
    Description: "API Gateway endpoint URL for Prod stage for Fgo Farming Solver function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/fgo-farming-solver"
  FgoFarmingSolverFunction:
    Description: "Fgo Farming Solver Lambda Function ARN"
    Value: !GetAtt FgoFarmingSolverFunction.Arn
  FgoFarmingSolverFunctionRole:
    Description: "Implicit IAM Role created for Fgo Farming Solver function"
    Value: !GetAtt FgoFarmingSolverFunctionRole.Arn
