AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fgo-farming-solver

  Sample SAM Template for fgo-farming-solver

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev

Mappings:
  Bucket:
    dev:
      Name: fgodrop
    prod:
      Name: fgodrop
  Table:
    dev:
      Name: fgo-farming-solver-results
    prod:
      Name: fgo-farming-solver_results
  Api:
    dev:
      StageName: dev
    prod:
      StageName: prod

Resources:
  FgoFarmingSolverFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: fgo_farming_solver/
      Handler: main.handler
      Runtime: python3.9
      Environment:
        Variables:
          BUCKET_NAME: !FindInMap [Bucket, !Ref Env, Name]
          TABLE_NAME: !FindInMap [Table, !Ref Env, Name]
      Events:
        FgoFarmingSolverApi:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref FgoFarmingSolverApi
            Path: /
            Method: GET
      MemorySize: 1024
      Policies:
        - S3ReadPolicy:
            BucketName: !FindInMap [Bucket, !Ref Env, Name]
        - DynamoDBWritePolicy:
            TableName: !FindInMap [Table, !Ref Env, Name]

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FgoFarmingSolverFunction:
    Description: 'Fgo Farming Solver Lambda Function ARN'
    Value: !GetAtt FgoFarmingSolverFunction.Arn
  FgoFarmingSolverFunctionRole:
    Description: 'Implicit IAM Role created for Fgo Farming Solver function'
    Value: !GetAtt FgoFarmingSolverFunctionRole.Arn
