AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fgo-farming-solver

  Sample SAM Template for fgo-farming-solver

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  FgoFarmingSolverFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: fgo_farming_solver/
      Handler: main.handler
      Runtime: python3.8
      Events:
        FgoFarmingSolver:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fgo-farming-solver
            Method: get
      Policies:
        - S3ReadPolicy:
            BucketName: fgodrop
          

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FgoFarmingSolverApi:
    Description: "API Gateway endpoint URL for Prod stage for Fgo Farming Solver function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/fgo-farming-solver"
  FgoFarmingSolverFunction:
    Description: "Fgo Farming Solver Lambda Function ARN"
    Value: !GetAtt FgoFarmingSolverFunction.Arn
  FgoFarmingSolverFunctionRole:
    Description: "Implicit IAM Role created for Fgo Farming Solver function"
    Value: !GetAtt FgoFarmingSolverFunctionRole.Arn
